name: Build and Release

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: runner
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt pytest
      
    - name: Wait for PostgreSQL
      run: |
        for i in {1..10}; do
          pg_isready -h localhost -p 5432 && break || sleep 3
        done

    - name: Run Tests
      run: |
        pytest --maxfail=3 --disable-warnings

    - name: Build Binary
      run: |
        python -m pip install pyinstaller
        pyinstaller --onefile src/script.py

    - name: Upload Binary Artifact
      uses: actions/upload-artifact@v3
      with:
        name: binary
        path: dist/script